# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=768m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false

# Evita descargas de JDK/toolchain que bloquean Android Studio horas
org.gradle.java.installations.auto-download=false
